#!/usr/bin/env node --harmony

const app = require('../package.json');
/**
 * Normalize a port into a number, string, or false.
 */
let normalizePort = (val) => {
  let port = parseInt(val, 10);
  if (isNaN(port)) {
    // named pipe
    return val;
  }
  if (port >= 0) {
    // port number
    return port;
  }
  return false;
};

const server = require('../src/server');

const port = normalizePort(process.env.PORT || '3000');

server.listen(port,
  function () {
    console.log('%s version %s listening on port %s in %s mode.', app.name, app.version, port, process.env.NODE_ENV );
  });

